# Generated by Django 5.0.3 on 2024-04-06 20:07

import wss_app.accounts.models
import wss_app.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=wss_app.accounts.models.profile_picture_upload_path, validators=[wss_app.accounts.validators.validate_picture_file_size]),
        ),
    ]
