# Generated by Django 5.0.3 on 2024-04-03 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingwithoutexistinginfrastructure',
            name='floor_siphon',
        ),
    ]
