# Generated by Django 5.0.3 on 2024-04-01 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingwithexistinginfrastructure',
            name='bathroom_sink',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buildingwithexistinginfrastructure',
            name='bathtub',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buildingwithexistinginfrastructure',
            name='building_area',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='buildingwithexistinginfrastructure',
            name='building_residence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buildingwithexistinginfrastructure',
            name='dishwasher',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buildingwithexistinginfrastructure',
            name='floor_siphon',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buildingwithexistinginfrastructure',
            name='green_area',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='buildingwithexistinginfrastructure',
            name='kitchen_sink',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buildingwithexistinginfrastructure',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buildingwithexistinginfrastructure',
            name='property_area',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='buildingwithexistinginfrastructure',
            name='shower',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buildingwithexistinginfrastructure',
            name='toilet_seat',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buildingwithexistinginfrastructure',
            name='underground_parking_spots',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buildingwithexistinginfrastructure',
            name='washing_machine',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buildingwithoutexistinginfrastructure',
            name='bathroom_sink',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buildingwithoutexistinginfrastructure',
            name='bathtub',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buildingwithoutexistinginfrastructure',
            name='building_residence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buildingwithoutexistinginfrastructure',
            name='dishwasher',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buildingwithoutexistinginfrastructure',
            name='floor_siphon',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buildingwithoutexistinginfrastructure',
            name='kitchen_sink',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buildingwithoutexistinginfrastructure',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buildingwithoutexistinginfrastructure',
            name='shower',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buildingwithoutexistinginfrastructure',
            name='toilet_seat',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buildingwithoutexistinginfrastructure',
            name='washing_machine',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infrastructureproject',
            name='existing_pavement',
            field=models.CharField(choices=[('Asphalt', 'Asphalt'), ('Concrete', 'Concrete'), ('Stone paving', 'Stone paving'), ('Pavers', 'Pavers'), ('None', 'None')]),
        ),
    ]
