# Generated by Django 5.0.3 on 2024-04-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_buildingwithoutexistinginfrastructure_floor_siphon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructureproject',
            name='new_plumbing_diameter',
            field=models.CharField(choices=[('DN90', 'DN90'), ('DN110', 'DN110'), ('DN125', 'DN125'), ('DN160', 'DN160'), ('DN200', 'DN200'), ('DN225', 'DN225'), ('DN250', 'DN250'), ('DN315', 'DN315'), ('DN355', 'DN355'), ('DN400', 'DN400')]),
        ),
        migrations.AlterField(
            model_name='infrastructureproject',
            name='new_sewer_diameter',
            field=models.CharField(choices=[('DN315', 'DN315'), ('DN400', 'DN400'), ('DN500', 'DN500'), ('DN630', 'DN630'), ('DN800', 'DN800'), ('DN1000', 'DN1000')]),
        ),
    ]
