# Generated by Django 5.0.3 on 2024-04-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_buildingwithexistinginfrastructure_bathroom_sink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingwithexistinginfrastructure',
            name='name',
            field=models.CharField(default='NewProject', max_length=100),
        ),
        migrations.AlterField(
            model_name='buildingwithoutexistinginfrastructure',
            name='name',
            field=models.CharField(default='NewProject', max_length=100),
        ),
    ]
