# Generated by Django 5.0.3 on 2024-04-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_buildingwithexistinginfrastructure_project_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingwithexistinginfrastructure',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='buildingwithoutexistinginfrastructure',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
