# Generated by Django 5.0.3 on 2024-04-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_buildingwithexistinginfrastructure_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingwithexistinginfrastructure',
            name='building_residence',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='buildingwithexistinginfrastructure',
            name='name',
            field=models.CharField(error_messages='You must specify name', max_length=100),
        ),
        migrations.AlterField(
            model_name='buildingwithoutexistinginfrastructure',
            name='building_residence',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='buildingwithoutexistinginfrastructure',
            name='name',
            field=models.CharField(error_messages='You must specify name', max_length=100),
        ),
    ]
