# Generated by Django 5.0.3 on 2024-04-01 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_buildingwithexistinginfrastructure_building_residence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingwithexistinginfrastructure',
            name='building_residence',
            field=models.PositiveIntegerField(error_messages={'required': 'You must have at least one residence'}),
        ),
        migrations.AlterField(
            model_name='buildingwithexistinginfrastructure',
            name='name',
            field=models.CharField(error_messages={'required': 'You must specify a name'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='buildingwithoutexistinginfrastructure',
            name='building_residence',
            field=models.PositiveIntegerField(error_messages={'required': 'You must have at least one residence'}),
        ),
        migrations.AlterField(
            model_name='buildingwithoutexistinginfrastructure',
            name='name',
            field=models.CharField(error_messages={'required': 'You must specify a name'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='infrastructureproject',
            name='project_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
