# Generated by Django 5.0.3 on 2024-04-01 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_buildingwithexistinginfrastructure_building_residence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingwithexistinginfrastructure',
            name='building_residence',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='buildingwithoutexistinginfrastructure',
            name='building_residence',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
    ]
