# Generated by Django 5.0.3 on 2024-04-01 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_buildingwithexistinginfrastructure_building_residence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingwithexistinginfrastructure',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='buildingwithoutexistinginfrastructure',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
